<a href="https://colab.research.google.com/github/odam2323/odam2323/blob/main/ejercicioEstadisticoNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = "https://drive.google.com/uc?export=view&id=13qgLt1GChCQgM3eb5SU5PoZjR7NYmSil" alt = "Encabezado MLDS" width = "100%">  </img>

# **Tarea 1 - Introducción al análisis de datos: *Python* y *NumPy***
---
Esta tarea le permitirá practicar y aplicar las habilidades adquiridas para la escritura de código en el lenguaje de programación *Python* y su librería de numérica *NumPy*.

> **Nota:** Esta tarea va a ser calificada en la plataforma **[UNCode](https://juezun.github.io/)**. Para esto, en cada ejercicio se indicará si es calificable o no, también los lugares donde debe escribir su código sin modificar lo demás con un aproximado de cantidad de líneas a escribir. No se preocupe si su código toma más líneas, esto es simplemente un aproximado destinado a que pueda replantear su estrategia si el código está tomando más de las esperadas. No es un requisito estricto y soluciones más largas también son válidas. Al finalizar, para realizar el envío (*submission*), descargue el notebook como un archivo **`.ipynb`** y haga su entrega a través de la plataforma de aprendizaje.

Ejecute las siguientes celdas para importar las librerías y conocer sus respectivas versiones.

In [ ]:
#TEST_CELL
import numpy as np

In [ ]:
#TEST_CELL
!python --version
print('NumPy', np.__version__)

Python 3.12.11
NumPy 2.0.2


Este material fue realizado con las siguientes versiones:

*  *Python*: 3.11.13
*  *NumPy*:  2.0.2


## **Conexión UNCode**

In [ ]:
%%capture
!pip install rlxcrypt
!wget --no-cache -O session.pye -q https://raw.githubusercontent.com/JuezUN/INGInious/master/external%20libs/session.pye

In [ ]:
import rlxcrypt
import session

grader = session.LoginSequence("AYVDD-GroupMLDS-1-2025-2@tarea_1")

Please enter your password: ··········


## **Contexto**

El "Caesars Palace", uno de los casinos más importantes de Las Vegas, siempre ha prometido una experiencia de juego inigualable. Sin embargo, detrás del brillo de las luces y el sonido de las máquinas tragamonedas, yace un desafío constante: asegurar la integridad del juego y la equidad para todos los jugadores. En esta búsqueda de transparencia y confianza, el "Caesars Palace" los contrató para desarrollar una serie de algoritmos que permitirán verificar la legitimidad de los jugadores y sus victorias.



<center>
  <img src = "https://drive.google.com/uc?export=view&id=1w95x5h5-nKRtyuRcfQb84mtooqpdtOrQ" alt = "Casino" width = "80%">  
  </img>
</center>


## **1. Valor esperado**
---

Como parte del equipo de desarrollo del "Caesars Palace", su tarea es emplear sus habilidades de programación para analizar la integridad de los dados utilizados en el juego  Craps (dados). Este juego se basa en el resultado del lanzamiento de dos dados, sobre el cual los jugadores apuestan; finalmente, los que hayan tenido una mayor proximidad al resultado observado son declarados ganadores en cada ronda, tras la cual podrán retirar su dinero o apostar nuevamente.

<center>
  <img src = "https://drive.google.com/uc?export=view&id=1yQxMqnfl5ZSeu_TxKRLlH8NF8W0U07X6" alt = "Dados" width = "80%">  
  </img>
</center>

Una de las formas en que la integridad del juego puede verse afectada es la presencia de dados cargados. Con frecuencia, los lanzamientos van desgastándolos, haciendo más probable que caigan en algunas caras que en otras. Algunos jugadores experimentados son capaces de darse cuenta de este fenómeno, aprovechándolo para apostar por los valores más probables y así mejorar su racha de victorias.


Para enfrentar este fenómeno, el casino ha registrado los resultados de varios lanzamientos de un dado a la vez en múltiples partidas. Esta información se le provee en forma de un arreglo de `numpy`, donde cada registro corresponde al resultado en un lanzamiento. **A partir de esto, le solicita que con esta información pueda detectar sin un dado está cargado o no por medio de la medición del valor esperado.**

En un dado justo y balanceado, el valor esperado se aproxima a 3.5. Si el valor esperado de los dados se desvía significativamente de este valor, es probable que esté cargado, lo que podría afectar la equidad del juego. Su análisis proporcionará información crucial para asegurar la integridad y la transparencia del casino.

Recuerde que el valor esperado puede calcularce como :

$$ E[x] = \frac{1}{n} \sum x_i $$

donde:
* $E[x]$ corresponde al valor esperado
* $n$ numero de lanzamientos
* $x_i$ el valor obtenido en cada uno de los lanzamientos.

Adicionalmente, el casino le solicita que el cálculo se realice de la forma más eficiente posible, priorizando el rendimiento y la optimización del código. Por esta razón, se solicita evitar el uso de funciones predefinidas de NumPy como `np.mean` y `np.sum`, ya que pueden introducir sobrecarga computacional en este caso particular. En su lugar, se requiere implementar el cálculo del valor esperado de manera manual, utilizando multiplicaciones matriciales.


**Parámetros**

* `lanzamientos`: arreglo de numpy con los resultados de lanzamientos de 1 a 6.

**Retorna**

* `results`: Valor promedio de los lanzamientos

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* La suma de todos los valores de un vector fila se puede obtener realizando el producto matricial por un vector columna de unos.


In [ ]:
# FUNCIÓN CALIFICADA: valor_esperado(lanzamientos)
def valor_esperado(lanzamientos):
    """
    lanzamientos: un arreglo de NumPy con valores enteros no negativos. Contiene los valores obtenidos en los ultimos 10 lanzamientos.

    Retorna un flotante correspondiente al valor esperado de los lanzamientos.
    """
    ### ESCRIBA SU CÓDIGO AQUÍ ###
    # Reemplace la palabra None por el código correspondiente
    # ~ 6 líneas de código

    # Convierta los lanzamiento en vector fila

    vector_fila = np.array(lanzamientos)

    # Cree un vector columna de unos con el mismo tamaño de la variable
    # lanzamientos

    vector_columna = np.ones(vector_fila.size)

    # multiplique los vectores obtenidos

    multiplicacion = vector_fila*vector_columna

    resultado = np.sum(multiplicacion)

    # divida el valor obtenido en el tamaño

    esperado = resultado / (vector_fila.size)

    ### FIN DEL CÓDIGO ###

    return esperado

In [ ]:
#TEST_CELL
np.random.seed(73)
lanzamientos = np.random.randint(1,7,100)
esperado = valor_esperado(lanzamientos)
print(esperado)

3.45


**Salida esperada**:

En este primer ejemplo se obtienen los elementos de la primera URL en el conjunto de datos:

```python
3.45
```

In [ ]:
#TEST_CELL
lanzamientos = np.array([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6])
esperado = valor_esperado(lanzamientos)
print(esperado)

3.5


**Salida esperada**:

```python
3.5
```

In [ ]:
#TEST_CELL
lanzamientos = np.array([1,6,1,4,1,2,2,5,5,4,1,1])
esperado = valor_esperado(lanzamientos)
print(esperado)

2.75


**Salida esperada**:

```python
2.75
```

### **Evaluar código**

In [ ]:
grader.run_test("Test 1_1", globals())

Test 1_1


In [ ]:
grader.run_test("Test 1_2", globals())

Test 1_2


## **2. Cálculo de probabilidades**
---
Si bien el proceso anterior permite determinar cuándo un dado está en condiciones adecuadas para su uso en el juego, esta información no puede utilizarse para identificar a los jugadores que aprovecharon esta situación a su favor. Para ello, el Caesars Palace desea que calcules la probabilidad de ocurrencia de cada cara del dado y utilices esta información para compararla con el comportamiento de los jugadores.

Se te proporcionará un arreglo de numpy que representa las partidas, donde cada registro corresponde a un lanzamiento. Ahora deberás determinar la probabilidad de cada cara siguiendo estos pasos:

1. **Contar la frecuencia de cada valor:** Recorre la lista de lanzamientos y cuenta cuántas veces aparece cada número del 1 al 6.
2. **Calcular la probabilidad:** Divide la frecuencia de cada valor entre el número total de lanzamientos.

📌 Ejemplo:

Si el número 3 aparece 20 veces en una lista de 100 lanzamientos, la probabilidad de obtener un 3 será:

$$\frac{20}{100} = 0.2 \quad o \quad 20\%$$  

Como resultado del análisis, deberás generar un arreglo llamado probabilidades, donde cada índice representará una de las caras del dado (del 1 al 6). El valor almacenado en cada posición corresponderá a la probabilidad calculada para esa cara.

* Ejemplo de estructura del arreglo:

    * `probabilidades[2]` contendrá la probabilidad de obtener un 3.
    * `probabilidades[5]` almacenará la probabilidad de obtener un 6

**Parámetros**

* `lanzamientos`: arreglo de numpy con los resultados de lanzamientos de 1 a 6.

**Retorna**

* `probabilidades`: Arreglo con los promedios de los lanzamientos

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* "Para realizar el proceso de conteo de frecuencias, se debe utilizar la indexación. Cada vez que encuentre un valor en la lista de lanzamientos, utilice dicho valor como índice para acceder a la posición correspondiente en un arreglo auxiliar y actualice la frecuencia en esa posición.



In [ ]:
# FUNCIÓN CALIFICADA: calcular_probabilidades(lanzamientos)
def calcular_probabilidades(lanzamientos):
    """
    lanzamientos:  un arreglo de NumPy con valores enteros no negativos. Contiene los valores obtenidos en los ultimos 10 lanzamientos.

    Retorna un arreglo con dimensión (6,) con las probabilidades para cad auna de las caras.
    """
    ### ESCRIBA SU CÓDIGO AQUÍ ###
    # Reemplace la palabra None por el código correspondiente
    # ~ 1-4 líneas de código

    # Desarrolle un bucle que recorra cada posicion del arreglo lanzamientos.

    vector = np.array(lanzamientos)

    # Change shape to (6,) as required by the docstring

    probabilidades = np.zeros(6)

    # identifique el valor ocurrido y sume 1 a la posicion correspondiente.

    for i in vector:
      probabilidades [i-1] += 1

    # Adjust index to be 0-based

    # Divide by the total number of launches to get probabilities

    probabilidades = probabilidades / np.sum(probabilidades)

    ### FIN DEL CÓDIGO ###

    return probabilidades

In [ ]:
#TEST_CELL
np.random.seed(73)
lanzamientos = np.random.randint(1,7,100)
probabilidades = calcular_probabilidades(lanzamientos)
print(np.sum(probabilidades))

1.0


**Salida esperada**:

```python
1.0
```

In [ ]:
#TEST_CELL
lanzamientos = np.array([1,1,1,2,2,2,3,3,3,3,4,4,4,5,5,5,5,6,6,6])
probabilidades = calcular_probabilidades(lanzamientos)
print(probabilidades)

[0.15 0.15 0.2  0.15 0.2  0.15]


**Salida esperada**:

```python
[0.15 0.15 0.2  0.15 0.2  0.15]
```

### **Evaluar código**

In [ ]:
grader.run_test("Test 2_1", globals())

Test 2_1


In [ ]:
grader.run_test("Test 2_2", globals())

Test 2_2


## **3. Probabilidades conjuntas**
---
Ahora que es posible determinar la probabilidad de ocurrencia de cada cara, el casino quiere calcular la probabilidad conjunta de que ocurra cada cara del dado y de que un jugador la seleccione en su apuesta. De esta manera, el Caesars Palace podrá medir la relación entre las apuestas de un jugador y el comportamiento del dado en la partida.

Para ello, el casino proporciona dos arreglos de numpy de Python:

* Una representa el comportamiento del dado.
* La otra contiene el patrón de apuestas de un jugador.

Con estos datos, deberás calcular:

**Matriz de probabilidades conjuntas:**  Es una matriz en la que cada celda representa la probabilidad observada de que:

* Al arrojar el dado, salga una cara específica.
* El jugador apueste por esa misma cara.

Características:

* La suma de las filas representa la probabilidad de ocurrencia de cada cara del dado.
* La suma de las columnas indica la probabilidad de que el jugador apueste por cada cara.

Esta matriz permite analizar la relación entre el comportamiento del dado y las decisiones del jugador en sus apuestas.

<center>
  <img src = "https://drive.google.com/uc?export=view&id=1DXXn4XHQfoNPtc8sHmhWdxJXgu0gPkko" alt = "Matriz Probabilidades Conjuntas" width = "80%">  
  </img>
</center>

**Matriz de probabilidades ideales:** En esta matriz, cada celda muestra la probabilidad teórica de que un número salga en el dado y que el jugador apueste por él, asumiendo que ambos eventos son independientes.

Se calcula con la siguiente fórmula:

$$P(cara_i  \cap apuesta_j) = P(cara_i ) * P(apuesta_j)$$

Donde:

* $P(cara_i   \cap apuesta_j)$ representa la probabilidad conjunta de que al arrojar el dado caiga una cara particular y que el jugador apueste por dicha cara

* $P(cara_i )$ representa la probabilidad de que ocurra la cara i
* $P(apuesta_j)$ representa la probabilidad de que el jugador apueste por la cara j

<center>
<img src = "https://drive.google.com/uc?export=view&id=17BXvRd2iBtoreXkf2Yu_sPmq286Q8tef" alt = "Matriz Probabilidades Ideales" width = "80%">  
</img>
</center>

📌 Ejemplo:

Si queremos calcular la probabilidad de obtener un '3' en el lanzamiento y que el jugador apueste por la cara '5', debemos multiplicar la probabilidad individual de obtener un '3' al lanzar el dado por la probabilidad individual de obtener un '5' en las apuestas del jugador

$$P(3  \cap 5) = P(3) * P(5)$$

El observar la cercanía entre ambas matrices le permitirá al casino entender que tan asociado está el comportamiento del jugador al comportamiento del dado. Entre más parecidas sean entre sí, el jugador tendrá un comportamiento NO relacionado con el histórico de lanzamiento del dado.



**Parámetros**

* `lanzamientos`: arreglo de numpy con los resultados de lanzamientos de 1 a 6.
* `apuestas`: arreglo de numpy con las apuestas de los jugadores de 1 a 6.

**Retorna**

* `probabilidades_ideales`: Arreglo con las probabilidades teóricas
* `probabilidades_medidas`: Arreglo con las probabilidades obtenidas

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* Para obtener la matriz de probabilidades conjuntas de forma eficiente, se puede aprovechar el producto externo. Esta operación permite multiplicar cada elemento de un vector por todos los elementos de otro vector, generando una matriz con todas las posibles combinaciones de productos.

En este caso, podemos utilizar el producto externo para multiplicar el vector de probabilidades individuales del  dado por el vector de probabilidades de las apuestas. El resultado será una matriz donde cada elemento (i, j) representará la probabilidad conjunta de obtener el valor i en el primer dado y el valor j en el segundo dado.



In [ ]:
# FUNCIÓN CALIFICADA: probabiliades_conjuntas(lanzamientos_1, lanzamientos_2)
def probabiliades_conjuntas(lanzamientos, apuestas):
    """
    lanzamientos:  un arreglo de NumPy con valores enteros no negativos. Contiene los valores obtenidos en los ultimos n lanzamientos del dado.
    apuestas":  un arreglo de NumPy con valores enteros no negativos. Contiene los valores obtenidos en los ultimos n apuestas del jugador.

    Retorna dos matrices con dimensión (6,6) con las probabilidades descritas.
    """
    probabilidades_ideales = None
    probabilidades_medidas = None

    #Calcule la probabiliadad de ocurrencia de las caras para los lanzamientos

    probabilidades_lanzamientos = calcular_probabilidades(lanzamientos)

    #Calcule la probabiliadad de ocurrencia de las caras para las apueats

    probabilidades_apuestas = calcular_probabilidades(apuestas)

    #Calcule la matriz de probabilidades ideales

    probabilidades_ideales = np.outer(probabilidades_lanzamientos,probabilidades_apuestas)

    #En un bucle recorra los avlroes obtenidos para las apuestas y lanzamainetos simulatenamente

    #Cuente e indexe en la matriz de probabilidades conjuntas la cantidad de veces que ocurre la convinación cara_i y apuesta_j

    probabilidades_medidas = np.zeros((6,6))

    for i,j in zip(lanzamientos, apuestas):
      probabilidades_medidas[i-1][j-1]+=1

    probabilidades_medidas = probabilidades_medidas/np.sum(probabilidades_medidas)


    return probabilidades_ideales, probabilidades_medidas


In [ ]:
## TEST
##############################################
########### SOLUCIÓN (BORRAR) ################
##############################################
def probabiliades_conjuntas(lanzamientos, apuestas):
    """
    lanzamientos:  un arreglo de NumPy con valores enteros no negativos. Contiene los valores obtenidos en los ultimos n lanzamientos del dado.
    apuestas":  un arreglo de NumPy con valores enteros no negativos. Contiene los valores obtenidos en los ultimos n apuestas del jugador.

    Retorna dos matrices con dimensión (6,6) con las probabilidades descritas.
    """
    probabilidades_lanzamientos = calcular_probabilidades(lanzamientos)
    probabilidades_apuestas = calcular_probabilidades(apuestas)

    probabilidades_ideales = probabilidades_lanzamientos @ probabilidades_apuestas

    probabilidades_medidas = np.zeros((6,6))
    for i,j in zip(lanzamientos, apuestas):
        probabilidades_medidas[i-1][j-1]+=1
    probabilidades_medidas = probabilidades_medidas/np.sum(probabilidades_medidas)

    return probabilidades_ideales, probabilidades_medidas

In [ ]:
#TEST_CELL
np.random.seed(73)
lanzamientos = np.random.randint(1,7,10000)
apuestas = np.random.randint(1,7,10000)
probabiliades_conjuntas(lanzamientos, apuestas)

(array([[0.02771028, 0.02674308, 0.02671084, 0.02661412, 0.02642068,
         0.027001  ],
        [0.02882763, 0.02782143, 0.02778789, 0.02768727, 0.02748603,
         0.02808975],
        [0.02910267, 0.02808687, 0.02805301, 0.02795143, 0.02774827,
         0.02835775],
        [0.02899953, 0.02798733, 0.02795359, 0.02785237, 0.02764993,
         0.02825725],
        [0.02910267, 0.02808687, 0.02805301, 0.02795143, 0.02774827,
         0.02835775],
        [0.02815722, 0.02717442, 0.02714166, 0.02704338, 0.02684682,
         0.0274365 ]]),
 array([[0.0279, 0.0279, 0.0266, 0.0264, 0.0261, 0.0263],
        [0.0288, 0.0278, 0.0272, 0.0284, 0.0279, 0.0276],
        [0.027 , 0.0266, 0.0296, 0.0295, 0.0277, 0.0289],
        [0.0293, 0.0282, 0.0243, 0.0279, 0.0285, 0.0305],
        [0.029 , 0.0294, 0.0297, 0.0252, 0.0287, 0.0273],
        [0.0299, 0.026 , 0.0283, 0.0277, 0.025 , 0.0269]]))

**Salida esperada**:

```python
(array([[0.02771028, 0.02674308, 0.02671084, 0.02661412, 0.02642068,
         0.027001  ],
        [0.02882763, 0.02782143, 0.02778789, 0.02768727, 0.02748603,
         0.02808975],
        [0.02910267, 0.02808687, 0.02805301, 0.02795143, 0.02774827,
         0.02835775],
        [0.02899953, 0.02798733, 0.02795359, 0.02785237, 0.02764993,
         0.02825725],
        [0.02910267, 0.02808687, 0.02805301, 0.02795143, 0.02774827,
         0.02835775],
        [0.02815722, 0.02717442, 0.02714166, 0.02704338, 0.02684682,
         0.0274365 ]]),
 array([[0.0279, 0.0279, 0.0266, 0.0264, 0.0261, 0.0263],
        [0.0288, 0.0278, 0.0272, 0.0284, 0.0279, 0.0276],
        [0.027 , 0.0266, 0.0296, 0.0295, 0.0277, 0.0289],
        [0.0293, 0.0282, 0.0243, 0.0279, 0.0285, 0.0305],
        [0.029 , 0.0294, 0.0297, 0.0252, 0.0287, 0.0273],
        [0.0299, 0.026 , 0.0283, 0.0277, 0.025 , 0.0269]]))
```

In [ ]:
#TEST_CELL
lanzamientos = np.array([1,1,1,2,2,2,3,3,3,3,4,4,4,5,5,5,5,6,6,6])
apuestas = np.array([1,1,1,2,2,2,3,3,3,3,4,4,4,5,5,5,5,6,6,6])
probabiliades_conjuntas(lanzamientos, apuestas)

(array([[0.0225, 0.0225, 0.03  , 0.0225, 0.03  , 0.0225],
        [0.0225, 0.0225, 0.03  , 0.0225, 0.03  , 0.0225],
        [0.03  , 0.03  , 0.04  , 0.03  , 0.04  , 0.03  ],
        [0.0225, 0.0225, 0.03  , 0.0225, 0.03  , 0.0225],
        [0.03  , 0.03  , 0.04  , 0.03  , 0.04  , 0.03  ],
        [0.0225, 0.0225, 0.03  , 0.0225, 0.03  , 0.0225]]),
 array([[0.15, 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.15, 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.2 , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.15, 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.2 , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.15]]))

**Salida esperada**:

```python
(array([[0.0225, 0.0225, 0.03  , 0.0225, 0.03  , 0.0225],
        [0.0225, 0.0225, 0.03  , 0.0225, 0.03  , 0.0225],
        [0.03  , 0.03  , 0.04  , 0.03  , 0.04  , 0.03  ],
        [0.0225, 0.0225, 0.03  , 0.0225, 0.03  , 0.0225],
        [0.03  , 0.03  , 0.04  , 0.03  , 0.04  , 0.03  ],
        [0.0225, 0.0225, 0.03  , 0.0225, 0.03  , 0.0225]]),
 array([[0.15, 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.15, 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.2 , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.15, 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.2 , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.15]]))
```

### **Evaluar código**

In [ ]:
grader.run_test("Test 3_1", globals())

Test 3_1


In [ ]:
grader.run_test("Test 3_2", globals())

Test 3_2



## **Evaluación**
**¡Felicitaciones!** Ha terminado la tarea de la Unidad 1. ¡Excelente trabajo!



In [ ]:
grader.submit_task(globals())

Test 1_1
Test 1_2
Test 2_1
Test 2_2
Test 3_1
Test 3_2



## **Créditos**
* **Profesor:** [Felipe Restrepo Calle](https://ferestrepoca.github.io/), [Luis Fernando Niño](https://dis.unal.edu.co/~ferestrepoca/)
* **Asistentes docentes:**
    - [Juan Sebastián Malagón Torres](https://www.linkedin.com/in/juan-sebastian-lara-ramirez-43570a214/).
* **Diseño de imágenes:**
    - [Sebastián Daniel Moreno Martinez](mailto:rsuperlano@unal.edu.co).
* **Coordinador de virtualización:**
    - [Edder Hernández Forero](https://www.linkedin.com/in/edder-hernandez-forero-28aa8b207/).
    
**Universidad Nacional de Colombia** - *Facultad de Ingeniería*